### DISCUSSION TITLE
Using tabs in blocks

### DISCUSSION THREAD

**Discussion by damsfx** [wintercms/wn-blocks-plugin#9] [Q&A] [answered]
I'm trying to get my block to have tabs, one for general fields and the second for some extra parameters.  
I've try using `nestedform` without success.

Does one of you have ever done it and share some though.

**Comment by LukeTowers** [comment]
See the button block, it's not using tabs right now but it's the general setup of how you would. What have you tried? I know I've done it before on some other projects but I don't have access to them at the moment to pull up an example.

**Reply by damsfx** [reply]
What I have tried is to have a generic section where I can add some blocks in a tab, and add section parameters in another tab.  
Something like this : 
![Section_params](https://user-images.githubusercontent.com/282242/235670218-c0482d44-c375-4d84-98df-8de658c287a4.gif)

What I've tried with blocks : 
```yaml
name: Section
description: Section with params
icon: icon-th-large
context: ["test"]
fields:
    content:
        label: Section
        type: nestedform
        form:
            fields:
                label:
                    label: Label test field
                    span: full
                    type: text
            tabs:
                section:
                    tab: Content
                    label: Section
                    span: full
                    type: blocks
                    ignore:
                        - section
                bg_color:
                    tab: Params
                    label: Background color
                    type: colorpicker
                full_size:
                    tab: Params
                    label: Color
                    type: switch
==
```
At this point, only `content/label` field is rendered.
