### ISSUE TITLE
Theme's block file not found

### ISSUE THREAD

**Issue by damsfx** [wintercms/wn-blocks-plugin#39]
The latest commit https://github.com/wintercms/wn-blocks-plugin/commit/9c9116921572bbacbc00ee2691854583103aee46 give me the following error :
```bash 
"The specified file name [themes.acme::lang.blocks.button.name.block] is invalid." 
on line 502 of P:\_Sites\acme\vendor\winter\storm\src\Halcyon\Builder.php
```

**and I can't edit any of the site model**.

The block definition is : 
```yaml
name: themes.acme::lang.blocks.button.name
description: themes.acme::lang.blocks.button.description
icon: icon-caret-square-o-right
tags: ["pages"]
fields:
    ...
```

This doesn't seem to be related to the use of a translation key in the block name, but after several tests, i**t seems necessary for my theme's blocks to have the `name` property equal to the file name**.

As soon as the block name is equal to the file name, the error disappears.
